### ISSUE TITLE
Pytables difficult to install on apple silicon

### ISSUE THREAD

**Issue by genomematt** [CountESS-Project/CountESS#6]
tables relies on the hdf5 library and is problematic to the point that it appears to have been yanked as a wheel for some versions. Source and wheel distributions are not working for 3.10 at least and conda is the only real option, and that only works for very specific versions.

Given this fragility is tables essential for basic operation?
If not we should consider making it an optional dependency.

**Comment by genomematt** [comment]
Ok I have a solution that works now. Conda will not install pytables but it will install the hdf5 dependency if you ask it to directly. The source build then works correctly.
If we do need tables we should document this install procedure.

**Comment by nickzoic** [comment]
Right, okay. Yeah, 'tables' is an optional dependency of pandas, needed for `pandas.HDFStore` I think ...
but if installing it is that much of a PITA we could either:

a) make HDF an optional feature for CountESS, eg: `pip install countess[hdf]` and the HDF5 plugin can be made unavailable if tables is unavailable.

b) break HDF reading and writing out into a non-builtin plugin package w/ its own requirement for tables, eg: `pip install countess_hdf` will pull in the extra plugin and also the requirement for tables.

c) use some other HDF library instead (h5py for example)

Since everything is a plugin, it doesn't really make a lot of difference to the user if a plugin is bundled into CountESS or in a separate package.

What are your thoughts?

**Comment by genomematt** [comment]
I would suggest a) pip install countess[hdf]

**Comment by nickzoic** [comment]
OK this is merged in v0.0.21, and I think it's okay, so long as we document the optional `[hdf]` option.
